# For use with the Rest Client VSCode extension (humao.rest-client)

@baseUrl= https://flask-api-nymajona.rahtiapp.fi

GET {{baseUrl}}

###

POST {{baseUrl}}
Content-Type: application/json

{
    "testkey": "Test value"
}

###

GET {{baseUrl}}/services

###

GET {{baseUrl}}/orders

###

POST {{baseUrl}}/services
Content-Type: application/json

{ 
    "name": "TestService",
    "price": 30
}

###

POST {{baseUrl}}/orders
Content-Type: application/json

{ 
    "service": "TestService",
    "cabin_id": "123123123123123123"
}

###

DELETE {{baseUrl}}/orders
Content-Type: application/json

{ 
    "id": 1
}