# For use with the Rest Client VSCode extension (humao.rest-client)

@baseUrl=http://127.0.0.1:5000

GET {{baseUrl}}

###

POST {{baseUrl}}
Content-Type: application/json

{
    "testkey": "Test value"
}

###

GET {{baseUrl}}/services

###

POST {{baseUrl}}/services
Content-Type: application/json

{ 
    "name": "Laundrey",
    "price": 8
}